/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashSuggestionsRouteImport } from './routes/_dash.suggestions'
import { Route as DashRoadmapRouteImport } from './routes/_dash.roadmap'
import { Route as DashResumeRouteImport } from './routes/_dash.resume'
import { Route as DashResourcesRouteImport } from './routes/_dash.resources'
import { Route as DashRecruiterRouteImport } from './routes/_dash.recruiter'
import { Route as DashPricingRouteImport } from './routes/_dash.pricing'
import { Route as DashPortfolioRouteImport } from './routes/_dash.portfolio'
import { Route as DashMatchRouteImport } from './routes/_dash.match'
import { Route as DashLinkedinRouteImport } from './routes/_dash.linkedin'
import { Route as DashInterviewRouteImport } from './routes/_dash.interview'
import { Route as DashDashboardRouteImport } from './routes/_dash.dashboard'
import { Route as DashAtsRouteImport } from './routes/_dash.ats'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashSuggestionsRoute = DashSuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => DashRoute,
} as any)
const DashRoadmapRoute = DashRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => DashRoute,
} as any)
const DashResumeRoute = DashResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => DashRoute,
} as any)
const DashResourcesRoute = DashResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => DashRoute,
} as any)
const DashRecruiterRoute = DashRecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => DashRoute,
} as any)
const DashPricingRoute = DashPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DashRoute,
} as any)
const DashPortfolioRoute = DashPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashRoute,
} as any)
const DashMatchRoute = DashMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => DashRoute,
} as any)
const DashLinkedinRoute = DashLinkedinRouteImport.update({
  id: '/linkedin',
  path: '/linkedin',
  getParentRoute: () => DashRoute,
} as any)
const DashInterviewRoute = DashInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardRoute = DashDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashRoute,
} as any)
const DashAtsRoute = DashAtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ats': typeof DashAtsRoute
  '/dashboard': typeof DashDashboardRoute
  '/interview': typeof DashInterviewRoute
  '/linkedin': typeof DashLinkedinRoute
  '/match': typeof DashMatchRoute
  '/portfolio': typeof DashPortfolioRoute
  '/pricing': typeof DashPricingRoute
  '/recruiter': typeof DashRecruiterRoute
  '/resources': typeof DashResourcesRoute
  '/resume': typeof DashResumeRoute
  '/roadmap': typeof DashRoadmapRoute
  '/suggestions': typeof DashSuggestionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ats': typeof DashAtsRoute
  '/dashboard': typeof DashDashboardRoute
  '/interview': typeof DashInterviewRoute
  '/linkedin': typeof DashLinkedinRoute
  '/match': typeof DashMatchRoute
  '/portfolio': typeof DashPortfolioRoute
  '/pricing': typeof DashPricingRoute
  '/recruiter': typeof DashRecruiterRoute
  '/resources': typeof DashResourcesRoute
  '/resume': typeof DashResumeRoute
  '/roadmap': typeof DashRoadmapRoute
  '/suggestions': typeof DashSuggestionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_dash/ats': typeof DashAtsRoute
  '/_dash/dashboard': typeof DashDashboardRoute
  '/_dash/interview': typeof DashInterviewRoute
  '/_dash/linkedin': typeof DashLinkedinRoute
  '/_dash/match': typeof DashMatchRoute
  '/_dash/portfolio': typeof DashPortfolioRoute
  '/_dash/pricing': typeof DashPricingRoute
  '/_dash/recruiter': typeof DashRecruiterRoute
  '/_dash/resources': typeof DashResourcesRoute
  '/_dash/resume': typeof DashResumeRoute
  '/_dash/roadmap': typeof DashRoadmapRoute
  '/_dash/suggestions': typeof DashSuggestionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/ats'
    | '/dashboard'
    | '/interview'
    | '/linkedin'
    | '/match'
    | '/portfolio'
    | '/pricing'
    | '/recruiter'
    | '/resources'
    | '/resume'
    | '/roadmap'
    | '/suggestions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sitemap.xml'
    | '/ats'
    | '/dashboard'
    | '/interview'
    | '/linkedin'
    | '/match'
    | '/portfolio'
    | '/pricing'
    | '/recruiter'
    | '/resources'
    | '/resume'
    | '/roadmap'
    | '/suggestions'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/login'
    | '/sitemap.xml'
    | '/_dash/ats'
    | '/_dash/dashboard'
    | '/_dash/interview'
    | '/_dash/linkedin'
    | '/_dash/match'
    | '/_dash/portfolio'
    | '/_dash/pricing'
    | '/_dash/recruiter'
    | '/_dash/resources'
    | '/_dash/resume'
    | '/_dash/roadmap'
    | '/_dash/suggestions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/suggestions': {
      id: '/_dash/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof DashSuggestionsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/roadmap': {
      id: '/_dash/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof DashRoadmapRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/resume': {
      id: '/_dash/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof DashResumeRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/resources': {
      id: '/_dash/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof DashResourcesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/recruiter': {
      id: '/_dash/recruiter'
      path: '/recruiter'
      fullPath: '/recruiter'
      preLoaderRoute: typeof DashRecruiterRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/pricing': {
      id: '/_dash/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof DashPricingRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/portfolio': {
      id: '/_dash/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof DashPortfolioRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/match': {
      id: '/_dash/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof DashMatchRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/linkedin': {
      id: '/_dash/linkedin'
      path: '/linkedin'
      fullPath: '/linkedin'
      preLoaderRoute: typeof DashLinkedinRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/interview': {
      id: '/_dash/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof DashInterviewRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard': {
      id: '/_dash/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashDashboardRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/ats': {
      id: '/_dash/ats'
      path: '/ats'
      fullPath: '/ats'
      preLoaderRoute: typeof DashAtsRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashAtsRoute: typeof DashAtsRoute
  DashDashboardRoute: typeof DashDashboardRoute
  DashInterviewRoute: typeof DashInterviewRoute
  DashLinkedinRoute: typeof DashLinkedinRoute
  DashMatchRoute: typeof DashMatchRoute
  DashPortfolioRoute: typeof DashPortfolioRoute
  DashPricingRoute: typeof DashPricingRoute
  DashRecruiterRoute: typeof DashRecruiterRoute
  DashResourcesRoute: typeof DashResourcesRoute
  DashResumeRoute: typeof DashResumeRoute
  DashRoadmapRoute: typeof DashRoadmapRoute
  DashSuggestionsRoute: typeof DashSuggestionsRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashAtsRoute: DashAtsRoute,
  DashDashboardRoute: DashDashboardRoute,
  DashInterviewRoute: DashInterviewRoute,
  DashLinkedinRoute: DashLinkedinRoute,
  DashMatchRoute: DashMatchRoute,
  DashPortfolioRoute: DashPortfolioRoute,
  DashPricingRoute: DashPricingRoute,
  DashRecruiterRoute: DashRecruiterRoute,
  DashResourcesRoute: DashResourcesRoute,
  DashResumeRoute: DashResumeRoute,
  DashRoadmapRoute: DashRoadmapRoute,
  DashSuggestionsRoute: DashSuggestionsRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
